apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop-pratice
  region: us-east-1
  
managedNodeGroups:
  - name: roboshop-dev
    instanceTypes: ["c5a.large","c5.large","m5.large","c5n.large"]
    desiredCapacity: 2 # by default 3
    spot: true
    